### ISSUE TITLE
ios下，qt5.5+qtwebview在显示静态页面Edit框输入字符后点击按钮会闪退

### ISSUE THREAD

**Issue by dragonview** [minixxie/wpp-qt#2]
附上堆栈信息：
(lldb) bt
- thread #1: tid = 0x7cb50f, 0x0000000101292d04 avmedu`QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::data(this=0x0000000000000008) const + 12 at qscopedpointer.h:135, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
  - frame #0: 0x0000000101292d04 avmedu`QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::data(this=0x0000000000000008) const + 12 at qscopedpointer.h:135
    frame #1: 0x00000001006a4cdc avmedu`QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::pointer qGetPtrHelper<QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> > >(p=0x0000000000000008) + 24 at qglobal.h:983
    frame #2: 0x00000001006a55f8 avmedu`QWindow::d_func(this=0x0000000000000000) + 32 at qwindow.h:85
    frame #3: 0x00000001006b0710 avmedu`QWindow::setWindowState(this=0x0000000000000000, state=WindowNoState) + 148 at qwindow.cpp:1114
    frame #4: 0x00000001006ae900 avmedu`QWindow::showNormal(this=0x0000000000000000) + 32 at qwindow.cpp:1849
    frame #5: 0x000000010003c504 avmedu`wpp::qt::Wpp::realOnKeyboardVisibleChanged(this=0x0000000101c4b418) + 1624 at Wpp.cpp:237
    frame #6: 0x000000010003be7c avmedu`wpp::qt::Wpp::onKeyboardVisibleChanged(this=0x0000000101c4b418) + 128 at Wpp.cpp:143
    frame #7: 0x00000001000490ac avmedu`wpp::qt::Wpp::qt_static_metacall(_o=0x0000000101c4b418, _c=InvokeMetaMethod, _id=8, _a=0x000000017420ebc0) + 312 at moc_Wpp.cpp:320
    frame #8: 0x000000010127d7cc avmedu`QMetaCallEvent::placeMetaCall(this=0x00000001740b9f80, object=0x0000000101c4b418) + 176 at qobject.cpp:486
    frame #9: 0x000000010127f4e8 avmedu`QObject::event(this=0x0000000101c4b418, e=0x00000001740b9f80) + 404 at qobject.cpp:1246
    frame #10: 0x0000000101240efc avmedu`QCoreApplicationPrivate::notify_helper(this=0x000000015c623040, receiver=0x0000000101c4b418, event=0x00000001740b9f80) + 116 at qcoreapplication.cpp:1093
    frame #11: 0x0000000101240e60 avmedu`QCoreApplication::notify(this=0x000000016fddbe40, receiver=0x0000000101c4b418, event=0x00000001740b9f80) + 212 at qcoreapplication.cpp:1038
    frame #12: 0x000000010069ceec avmedu`QGuiApplication::notify(this=0x000000016fddbe40, object=0x0000000101c4b418, event=0x00000001740b9f80) + 76 at qguiapplication.cpp:1537
    frame #13: 0x0000000101240cf8 avmedu`QCoreApplication::notifyInternal(this=0x000000016fddbe40, receiver=0x0000000101c4b418, event=0x00000001740b9f80) + 192 at qcoreapplication.cpp:965
    frame #14: 0x000000010128a360 avmedu`QCoreApplication::sendEvent(receiver=0x0000000101c4b418, event=0x00000001740b9f80) + 112 at qcoreapplication.h:224
    frame #15: 0x0000000101242154 avmedu`QCoreApplicationPrivate::sendPostedEvents(receiver=0x0000000000000000, event_type=0, data=0x00000001740dc230) + 1336 at qcoreapplication.cpp:1593
    frame #16: 0x00000001012415e8 avmedu`QCoreApplication::sendPostedEvents(receiver=0x0000000000000000, event_type=0) + 52 at qcoreapplication.cpp:1451
    frame #17: 0x00000001000d4894 avmedu`QEventDispatcherCoreFoundation::processPostedEvents(this=0x00000001743a41a0) + 236 at qeventdispatcher_cf.mm:384
    frame #18: 0x00000001000d7068 avmedu`RunLoopSource<QEventDispatcherCoreFoundation>::process(info=0x00000001743a41b0) + 108 at qeventdispatcher_cf_p.h:139
    frame #19: 0x00000001846dc240 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
    frame #20: 0x00000001846db4e4 CoreFoundation`__CFRunLoopDoSources0 + 264
    frame #21: 0x00000001846d9594 CoreFoundation`__CFRunLoopRun + 712
    frame #22: 0x00000001846052d4 CoreFoundation`CFRunLoopRunSpecific + 396
    frame #23: 0x000000018e05b6fc GraphicsServices`GSEventRunModal + 168
    frame #24: 0x0000000189202f40 UIKit`UIApplicationMain + 1488
    frame #25: 0x00000001000a7458 avmedu`main(argc=1, argv=0x000000016fddf9f0) + 516 at qioseventdispatcher.mm:224
    frame #26: 0x0000000196a9aa08 libdyld.dylib`start + 4
    (lldb)

**Comment by minixxie** [comment]
fixed c6a13fee065de5010e259bd65472bc2bff58f9d0

Please verify. Thanks.

**Comment by dragonview** [comment]
![282a4342-1903-4454-8a3f-4eaeba61b468](https://cloud.githubusercontent.com/assets/12497354/9335143/eeb7cde6-4604-11e5-91e6-0d38dfa13ea4.jpg)

**Comment by dragonview** [comment]
高效啊！
